[package]
name = "pietro787/luacore"
description = "Framework pessoal para projetos simples"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["pietroi5kk"]
license = "MIT"
include = ["src/**", "wally.toml"]
exclude = ["rokit.toml", ".vscode"]

[dependencies]
